### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:8080/items/

###

GET http://localhost:8080/items/3

###
POST http://localhost:8080/items/
Content-Type: application/json

{
    "item_set": "F02",
    "item_description": "photo_camera",
    "item_type": "Parasonic",
    "item_category": 1,
    "serial_nr": "12345678",
    "lent_from": null,
    "return_date": null,
    "notes": ""
}
###
###
POST http://localhost:8080/items/
Content-Type: application/json

{
  "item_set": "F03",
  "item_description": "photo_camera",
  "item_type": "Parasonic",
  "item_category": 1,
  "serial_nr": "12345678",
  "lent_from": null,
  "return_date": null,
  "notes": ""
}
###
###
POST http://localhost:8080/items/
Content-Type: application/json

{
  "item_set": "F04",
  "item_description": "photo_camera",
  "item_type": "Parasonic",
  "item_category": 1,
  "serial_nr": "12345678",
  "lent_from": null,
  "return_date": null,
  "notes": ""
}
###

