### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:8080/devices/

###

GET http://localhost:8080/devices/3

###
POST http://localhost:8080/devices/
Content-Type: application/json

{
    "dev_id": 90,
    "dev_set": "F02",
    "dev_type": "Parasonic",
    "dev_category": 1,
    "dev_serial_nr": "12345678",
    "dev_asset_nr": "12345678",
    "lent_from": null,
    "return_date": null,
    "notes": ""
}

###
POST http://localhost:8080/excel-to-csv
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="deviceListAll.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< deviceListAll.xlsx
--WebAppBoundary--
###

GET http://localhost:8080/teacher

###

GET http://localhost:8080/student
Content-Type: */*

###

GET http://localhost:8080/room
Content-Type: */*

###

GET http://localhost:8080/eq

###

GET http://localhost:8080/cart

###

POST http://localhost:8080/cart/998/997

###

GET http://localhost:8080/cart/1

###
POST http://localhost:8080/excel-to-csv
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="deviceListAll.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< deviceListAll.xlsx
--WebAppBoundary--
###