name: GitHub Actions Demo
run-name: Build project
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

jobs:
  Backend:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'Application/Backend/pom.xml'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: Application/Backend
      - name: build docker
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --password-stdin -u ${{ github.actor }}
          docker build --file src/main/docker/Dockerfile --tag ${{ env.TAG }} .
          docker push ${{ env.TAG }}
        working-directory: Application/Backend
